package krisapps.tripplanner.misc.utils;

import javafx.geometry.Pos;
import javafx.scene.control.*;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import krisapps.tripplanner.PlannerApplication;
import org.jetbrains.annotations.Nullable;

import java.util.Optional;

public class PopupManager {

    public enum PopupType {
        EXPENSE_NAME_MISSING,
        EXPENSE_AMOUNT_MISSING,
        NOT_IMPLEMENTED,
        NEW_TRIP_WIZARD_EMPTY,
        NO_OPEN_PLAN,
        CALENDAR_EVENTS_NOT_CREATED,
        EVENTS_NOT_DELETED,
        EVENTS_DELETED,
        PLANNING_IN_PROGRESS,
        CALENDAR_INTEGRATION_DISABLED,
        NO_EVENTS,
        DOCUMENT_TEMPLATE_MISSING,
        PLAN_DATA_MISSING
    }

    public static Optional<ButtonType> showPredefinedPopup(PopupType type) {
        Alert alert = new Alert(null);
        alert.getDialogPane().getStylesheets().add(PlannerApplication.class.getResource("styles/styles.css").toExternalForm());
        switch (type) {
            case EXPENSE_NAME_MISSING -> {
                alert.setTitle("Cannot add expense entry");
                alert.setContentText("Please fill in the name of your expense and try again.");
                alert.setAlertType(Alert.AlertType.ERROR);
            }
            case EXPENSE_AMOUNT_MISSING -> {
                alert.setTitle("Cannot add expense entry");
                alert.setContentText("Please fill in the value of your expense and try again.");
                alert.setAlertType(Alert.AlertType.ERROR);
            }
            case PLANNING_IN_PROGRESS -> {
                alert.setTitle("Trip planning in progress!");
                alert.setContentText("A trip is currently open in Trip Planner. Do you want to discard this open plan, and start a new one?");
                alert.getButtonTypes().clear();
                alert.getButtonTypes().addAll(new ButtonType("Yes, discard current plan", ButtonBar.ButtonData.APPLY), ButtonType.CANCEL);
                alert.setAlertType(Alert.AlertType.CONFIRMATION);
            }
            case NEW_TRIP_WIZARD_EMPTY -> {
                alert.setTitle("Incomplete data!");
                alert.setContentText("Please fill in all the required fields (*) to start planning your trip.");
                alert.setAlertType(Alert.AlertType.ERROR);
            }
            case NO_OPEN_PLAN -> {
                alert.setTitle("No plan open yet");
                alert.setContentText("There are currently no open plans in the Planner. Open a plan in the Planner first.");
                alert.setAlertType(Alert.AlertType.WARNING);
            }
            case CALENDAR_EVENTS_NOT_CREATED -> {
                alert.setTitle("Event creation failed");
                alert.setContentText("An error prevented the Planner from creating the Google Calendar events for your trip. Check the logs for more info.");
                alert.setAlertType(Alert.AlertType.ERROR);
            }
            case EVENTS_DELETED -> {
                alert.setTitle("Delete events");
                alert.setContentText("Calendar events successfully deleted!");
                alert.setAlertType(Alert.AlertType.INFORMATION);
            }
            case NO_EVENTS -> {
                alert.setTitle("No events");
                alert.setContentText("Couldn't delete calendar events, since no events have been generated by the Planner.");
                alert.setAlertType(Alert.AlertType.ERROR);
            }
            case EVENTS_NOT_DELETED -> {
                alert.setTitle("Delete events");
                alert.setContentText("Couldn't delete calendar events. This might be due to there not being any events to delete, or an internal error.");
                alert.setAlertType(Alert.AlertType.ERROR);
            }
            case CALENDAR_INTEGRATION_DISABLED -> {
                alert.setTitle("Integration disabled");
                alert.setContentText("The Planner couldn't generate any calendar events, since the calendar integration is disabled.\nIf you wish to enable it, toggle the feature on the 'Set reminders' page of the Planner.");
                alert.setAlertType(Alert.AlertType.WARNING);
            }
            case DOCUMENT_TEMPLATE_MISSING -> {
                alert.setTitle("Document generation failed");
                alert.setContentText("No plan document template was found - please make sure the plan document is included in the resource folder of the program and try again.");
                alert.setAlertType(Alert.AlertType.ERROR);
            }
            case PLAN_DATA_MISSING -> {
                alert.setTitle("Document generation failed");
                alert.setContentText("There is not enough trip data for a planning document to be generated.");
                alert.setAlertType(Alert.AlertType.ERROR);
            }
            case NOT_IMPLEMENTED -> {
                alert.setTitle("Uh-oh!");
                alert.setContentText("This feature hasn't been implemented yet. Sorry!");
                alert.setAlertType(Alert.AlertType.WARNING);
            }
        }
        alert.setHeaderText(null);
        return alert.showAndWait();
    }

    public static Optional<ButtonType> showConfirmation(String title, String message, ButtonType optionA, ButtonType optionB) {
        if (!optionA.getButtonData().isCancelButton() && !optionB.getButtonData().isCancelButton()) {
            throw new IllegalArgumentException("Cannot show a confirmation dialog without a cancel option - please ensure that either optionA or optionB is a cancellation ButtonType");
        }

        Alert a = new Alert(Alert.AlertType.CONFIRMATION);
        a.getDialogPane().getStylesheets().add(PlannerApplication.class.getResource("styles/styles.css").toExternalForm());
        a.setTitle(title);
        a.setHeaderText(null);
        a.setContentText(message);
        a.getButtonTypes().clear();
        a.getButtonTypes().addAll(optionA, optionB);
        return a.showAndWait();
    }

    public static String showInputDialog(String title, String message, String inputLabel, @Nullable String inputValue) {
        Alert a = new Alert(Alert.AlertType.INFORMATION);

        a.getDialogPane().getStylesheets().add(PlannerApplication.class.getResource("styles/styles.css").toExternalForm());
        a.setTitle(title);
        a.setHeaderText(null);

        VBox root = new VBox();
        HBox.setHgrow(root, Priority.ALWAYS);

        Label msgLabel = new Label(message);
        Label inputBoxLabel = new Label(inputLabel);
        TextField inputField = new TextField();

        VBox inputContainer = new VBox();
        inputContainer.getChildren().add(inputBoxLabel);
        inputContainer.getChildren().add(inputField);
        inputContainer.setSpacing(5);

        inputBoxLabel.setStyle("-fx-font-weight: bold");

        HBox.setHgrow(inputContainer, Priority.ALWAYS);
        inputContainer.setAlignment(Pos.CENTER_LEFT);

        HBox.setHgrow(inputField, Priority.ALWAYS);

        root.getChildren().add(msgLabel);
        root.getChildren().add(inputContainer);
        root.setSpacing(5);

        inputField.setText(inputValue == null ? "" : inputValue);

        a.getDialogPane().setContent(root);

        Optional<ButtonType> response = a.showAndWait();
        if (response.isPresent()) {
            if (response.get() == ButtonType.OK) {
                return inputField.getText();
            }
        }
        return null;
    }


}
